### PR TITLE
1.1.1: Update entry point | Make alert un-cancelable

### PR DESCRIPTION
**Pull request by dac09**
- Fixes import issue #3
- Makes alerts for permission check un-cancellable

### CODE REVIEW

**Comment by dac09** [comment]
@ludo any chance you could review please? I'm ready to make changes if required.

**Comment by ludo** [comment]
Tested locally (with `npm link`): works! I'll publish v1.1.1 to npm as `@next` and test again.

**Comment by dac09** [comment]
Out of curiousity, does npm link work for you when you use android studio? I get gradle errors - it seems to not like symlinks. I've found command line to be okay with it though.

**Comment by ludo** [comment]
@dac09 I haven't tried inside Android Studio, I'm using it on the command line. But even there it doesn't work out of the box... I have to use a script I found in facebook/metro#1 to get it to work 😑

**Pull request merged**
